### ISSUE TITLE
Update policy network with real experiments

### ISSUE THREAD

**Issue by ioannanteka** [lightingghost/chemopt#10]
Hello,
I have a question on how the model learns from running actual experiments on chemical reactions. The readme states I should call _python realreaction.py_ after the pretrain finishes, but it looks to me that this only proposes new experiments with the weights of the RNN learned from the simulated data (mixture gaussian density functions) and it doesn't have a mechanism for updating the weights with information obtained from the experiments ran on the actual reaction. Is this correct? Is there any other script that performs an update of the weights?

**Comment by lightingghost** [comment]
Thank you for the question. The process to train the network on a real reaction includes doing polynomial fit of the optimization record, and feed the fitted function to the training pipeline. Unfortunately the ipython notebook script was located in another folder and lost during a hard disk failure. I can try to re-write it and update.

**Comment by ioannanteka** [comment]
Thank you for your reply. This makes sense. Just to clarify, the experiments you use to do the polynomial fit are the ones you obtain from the optimizer or you are using a number of initial experiments, say in a grid?

**Comment by lightingghost** [comment]
The experiments are those which we are using our optimizer to optimize, i.e. "obtain from the optimizer" if I understand correctly.

**Comment by ioannanteka** [comment]
Thank you. I will close the issue. It would be useful for future users if you add a comment in the readme regarding how you update the model with new experiments, even if you don't re-write the script that was lost.
