### ISSUE TITLE
config.json Need trainable_init section？

### ISSUE THREAD

**Issue by xiaoding945** [lightingghost/chemopt#3]
I clone your code ,then run "python lets_start.py ",However meet the mistake as fllows:
![image](https://user-images.githubusercontent.com/19324666/55868561-4964db00-5bb7-11e9-8ba4-e5767456074e.png)
then ,I read the config.json , Don't find the section "trainable_init", I hope get your reply!
![image](https://user-images.githubusercontent.com/19324666/55868691-92b52a80-5bb7-11e9-82ed-7ae2bbb52d7b.png)

 Best regards!!!

**Comment by lightingghost** [comment]
@xiaoding945 , I've updated the config.json file to include such an option. Sorry for the inconvenience.
