### ISSUE TITLE
Error when run "realreaction.py"

### ISSUE THREAD

**Issue by testpilot0** [lightingghost/chemopt#4]
Hi I have a problem to run "realreaction.py" and would appreciate any help.

I did run "lets_start.py" script with with default config.json  and created model . But I am getting error message every time I run "realreaction.py"

ValueError: Variable multi_input_rnn/proj/proj_weight already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

If I am changing config.jsom  to have "reuse": true then I am getting error  
 
ValueError: Trying to share variable lstm_3/w_gates, but specified shape (256, 512) and found shape (134, 512).
originally defined at:
  File "<ipython-input-4-edd4dda79f8f>", line 107, in main
    reuse=config.reuse)
  File "/home/jupyter/vtest/chemopt/rnn.py", line 87, in __init__
    self.cell = cell(**kwargs, name="lstm")
  File "/home/jupyter/vtest/chemopt/rnn.py", line 157, in __init__
    create_scope_now_=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)

**Comment by lightingghost** [comment]
@testpilot0 I just did a quick test on my computer and it worked just fine. Could you please check

1. Are you using tensorflow 1.2? I am not sure whether it will work on other `tf` versions.

2. Did you change `config.json` between running `lets_start.py` and `realreaction.py`? The `config.json` needs remain unchanged.

**Comment by testpilot0** [comment]
I am running tensor flow 1.13.1 let me install 1.2 and try again. And yes, I am changing config.json before running lets_start.py and do not change it before realreaction.py

**Comment by lightingghost** [comment]
@testpilot0 Sry I was using 1.12

**Comment by testpilot0** [comment]
I will try 1.12 then. When I run in 1.13 "lets_start.py" works fine and save model but produce warning

[WARNING] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py:966: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.

**But "realreaction.py" generate Error**. If I restart Kernel then Error goes away.

ValueError: Variable multi_input_rnn/proj/proj_weight already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/jupyter/vtest/chemopt/rnn.py", line 107, in __call__
    w = tf.get_variable('proj_weight', [hidden_size, tot_dim])
  File "/home/jupyter/vtest/chemopt/model.py", line 58, in step
    new_x, new_state = self.cell(x, fx, state)
  File "/home/jupyter/vtest/chemopt/model.py", line 71, in make_loss
    swap_memory=True

**Comment by lightingghost** [comment]
@testpilot0 Kernel? Are you using Jupyter? Did you reset the graph before running realreactions.py?

**Comment by testpilot0** [comment]
It does work after reset. Thank you
