### ISSUE TITLE
Why the separated architecture of two inputs vs one

### ISSUE THREAD

**Issue by oliverdutton** [lightingghost/chemopt#5]
I like the paper a lot. I have a question though.

In the model design why do you split the input x and y with separate matrices and gate vectors instead of inputting just one vector [x,y] with shared weights?

**Comment by lightingghost** [comment]
Thanks for your interest.

They are almost the same. If C = {A, B}, (here {} denotes vertical concatenation), then [x, y]C = xA + yB.

**Comment by oliverdutton** [comment]
Ah, I get it. 

Also, you explicitly return the final output x_t (proposed reaction conditions) along with the yield to the LSTM as input for the next timestep because otherwise it doesn't make the link between the LSTM output (h_t, part of the LSTM's hidden state) which inherently contains the proposed later reaction conditions (formed after passing h_t through the projection layer). From a theoretical standpoint this doesn't seem necessary, you can just input the yield? or does that lead to greatly increased training times/poorer performance?

**Comment by lightingghost** [comment]
Nice point. That is definitely possible, but I haven’t tried that.
