### ISSUE TITLE
Output conditions stagnate

### ISSUE THREAD

**Issue by eruxels** [lightingghost/chemopt#7]
Hello. Thank you for sharing your code here. I am however unable to get a coherent output.

Even though I was able to train my model and reach a mean error of about 0.05 for gaussian mixture functions, the testing part (i.e. the realreaction file) doesn't work for me: instead of converging to the maximum of my function, the reaction conditions almost don't vary from the first to the last step.
Please find attached the simulated yield function that I used for my tests, the outputs I get when I run realreaction.py, and the hyperparameters I used.

Did this problem ever occur to you? Would you have an idea of how I could solve it? Thank you very much in advance if you can help me.

![realreaction_plot](https://user-images.githubusercontent.com/52988408/61346142-4cdcc200-a88a-11e9-89ac-5df216c639bd.png)
![realreaction_stagnation](https://user-images.githubusercontent.com/52988408/61346143-4d755880-a88a-11e9-9dcb-fb97ebbd58ce.PNG)
![custom_RealReaction_func](https://user-images.githubusercontent.com/52988408/61346144-4d755880-a88a-11e9-8a42-2ce654c6a5eb.PNG)
![config](https://user-images.githubusercontent.com/52988408/61346225-75fd5280-a88a-11e9-8834-d10c069dce24.PNG)

**Comment by lightingghost** [comment]
chatted in email
